alias r='cd $(git rev-parse --show-toplevel)'
alias co='git checkout `git branch -a | fzf | sed -e "s|remotes\/origin\/||"`'
alias grep='grep -i'
alias cat='bat'
alias ls='exa'
alias ll='exa -la --git'
alias vi='nvim'
alias "?"=duck
alias "wiki"=wiki_search
alias wt="worktree.sh"
alias wt-checkout='cd `wt change`'
alias date='date -u +"%Y-%m-%dT%H:%M:%S%Z"'
alias fd='cd `find . -type d ! -name "*.gi*" ! -name "*.terrafor*" | fzf`'
alias tfuse='tfenv use `tfenv list | fzf`'
