---
- name: dotfile
  hosts: localhost
  become: false

  tasks:
  - name: Make a vimdid forlder
    file:
      path: ~/.vimdid
      state: directory

  - name: Make a NeoVIM config folder
    file:
      path: ~/.config/nvim
      state: directory

  - name: ZSH folder
    file:
      path: ~/.zsh/plugins
      state: directory

  - name: ZSH zsh-vim-mode
    git:
      repo: https://github.com/softmoth/zsh-vim-mode.git
      dest: ~/.zsh/plugins/zsh-vim-mode

  - name: Install deps
    package:
      name: "{{ item }}"
      state: present
    become: true
    loop:
    - curl
    - apt-transport-https
    - hwinfo
    - linux-tools-generic
      # alacritty
    - libxcb-shape0-dev
    - libxcb-render0-dev
    - libxcb-xfixes0-dev
      # bevy_chess stuff
    - libasound2-dev 
    - libx11-dev
    - librust-libudev-sys-dev
    - libasound2-dev

  - name: Install packages
    package:
      name: "{{ item }}"
      state: present
    become: true
    loop:
    - neovim
    - tmux
    - fzf
    - tldr
    - cmake 
      #- exa
    - ripgrep
    - zsh-syntax-highlighting
    - w3m
    - shellcheck
    - ctags
      #- bat
      #- aws-sam-cli
    - composer
      #- lf
    - autojump

  - name: Clonning Tmux themepack
    git:
      repo: https://github.com/jimeh/tmux-themepack.git
      dest: "~/.tmux-themepack"

  - name: making some links
    file:
      src: "{{ item.file }}"
      dest: "{{ item.link }}"
      state: link
    loop:
      - file: ~/git/dotfiles/init.vim
        link: ~/.config/nvim/init.vim
      - file: ~/git/dotfiles/tmux.conf
        link: ~/.tmux.conf
      - file: ~/git/dotfiles/zshrc
        link: ~/.zshrc
      - file: ~/git/dotfiles/gitignore_global
        link: ~/.gitignore_global
      - file: ~/git/dotfiles/bin
        link: ~/bin

  # COC and language server stuff
  # Rust analyzer stuff
