---
- name: dotfile
  hosts: localhost
  become: false

  tasks:
  - name: Make a vimdid forlder
    file:
      path: ~/.vimdid
      state: directory

  - name: ZSH folder
    file:
      path: ~/.zsh/plugins
      state: directory

  - name: ZSH zsh-vim-mode
    git:
      repo: https://github.com/softmoth/zsh-vim-mode.git
      dest: ~/.zsh/plugins/zsh-vim-mode

  - name: ZSH zsh-autosuggestions
    git:
      repo: https://github.com/zsh-users/zsh-autosuggestions.git
      dest: ~/.zsh/plugins/zsh-autosuggestions

  # make sure this used brew
  - name: Install packages
    package:
      name: "{{ item }}"
      state: present
    loop:
    - neovim
    - tmux
    - fzf
    - tldr
    - cmake 
    - ripgrep
    - zsh-syntax-highlighting
    - w3m
    - shellcheck
    - ctags
    - composer
    - autojump
    - llvm
    - starship

  - name: making some links
    file:
      src: "{{ item.file }}"
      dest: "{{ item.link }}"
      state: link
    loop:
      - file: ~/git/dotfiles/nvim/
        link: ~/.config/nvim/
      - file: ~/git/dotfiles/tmux.conf
        link: ~/.tmux.conf
      - file: ~/git/dotfiles/zshrc
        link: ~/.zshrc
      - file: ~/git/dotfiles/gitignore_global
        link: ~/.gitignore_global
      - file: ~/git/dotfiles/bin
        link: ~/bin
