---
- name: dotfile
  hosts: localhost
  become: false

  tasks:
  - name: Make some folders
    file:
      path: "{{ item }}"
      state: directory
    loop:
      - ~/.vimdid
      - ~/.zsh/plugins
      - ~/.config
      - ~/.config/alacritty

  - name: ZSH zsh-vim-mode
    git:
      repo: https://github.com/softmoth/zsh-vim-mode.git
      dest: ~/.zsh/plugins/zsh-vim-mode

  - name: ZSH zsh-autosuggestions
    git:
      repo: https://github.com/zsh-users/zsh-autosuggestions.git
      dest: ~/.zsh/plugins/zsh-autosuggestions

  # Update homebrew and upgrade all packages
  - community.general.homebrew:
      update_homebrew: true
      upgrade_all: true

  # make sure this used brew
  - name: brew packages
    community.general.homebrew:
      name: "{{ item }}"
      state: present
    loop:
        #    - alacritty # for some reason ansible thinks this is failing
    # - obsidian
    - tmux
    - fzf
    - tldr
    - ripgrep
    - bat
    - eza
    - shellcheck
    - llvm
    - starship
    - nvm
    - bacon
    - neomut
    - direnv
    - gh
    - lima
    - kind
    - moar
    - jq
    - yq

  - name: Languages with brew
    community.general.homebrew:
      name: "{{ item }}"
      state: present
    loop:
    - go

  - name: Install LSPs
    community.general.homebrew:
      name: "{{ item }}"
      state: present
    loop:
    - rust-analyzer
    - lua-language-server
    - gopls

  - name: Bleeding stuff
    community.general.homebrew:
      name: "{{ item }}"
      state: head
    loop:
    - neovim

  - name: making some links
    file:
      src: "{{ item.file }}"
      dest: "{{ item.link }}"
      state: link
      force: yes
    loop:
      - file: ~/personal/dotfiles/nvim
        link: ~/.config/nvim
      - file: ~/personal/dotfiles/tmux.conf
        link: ~/.tmux.conf
      - file: ~/personal/dotfiles/alacritty.yml
        link: ~/.config/alacritty/alacritty.yml
      - file: ~/personal/dotfiles/zshrc
        link: ~/.zshrc
      - file: ~/personal/dotfiles/gitignore_global
        link: ~/.gitignore_global
      - file: ~/personal/dotfiles/bin
        link: ~/bin

  - name: Download JetBrains Mono Nerd Font
    get_url:
      url: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/JetBrainsMono.zip
      dest: /tmp/JetBrainsMono.zip

  - name: Create a directory for JetBrains Mono Font
    file:
      path: /tmp/JetBrainsMono
      state: directory

  - name: Unarchive JetBrains Mono Font
    unarchive:
      src: /tmp/JetBrainsMono.zip
      dest: /tmp/JetBrainsMono
      remote_src: yes

  - name: Copy font files to the Fonts directory
    copy:
      src: /tmp/JetBrainsMono/
      dest: ~/Library/Fonts/
      mode: 0644

  - name: Remove downloaded and unzipped files
    file:
      path: "{{ item }}"
      state: absent
    loop:
      - /tmp/JetBrainsMono.zip
      - /tmp/JetBrainsMono

  - name: Download Rust installation script
    get_url:
      url: https://sh.rustup.rs
      dest: /tmp/rustup-init.sh
      mode: '0755'

  - name: Install Rust with default settings
    command: sh /tmp/rustup-init.sh -y
    args:
      creates: ~/.cargo/bin/rustc
